<h2>Schemas</h2>
<br />
<ul class="thumbnails" style="display: block;width: 100%;text-align: center;">
	<repeat group="{{ @schemas }}" key="{{ @ikey }}" value="{{ @schema }}">
		<li class="span4" style="display: inline-block;word-wrap: break-word;margin: 10px;">
		    <div class="thumbnail" style="width: 200px;display: inline-block;vertical-align: top;border:none;">
		    	<a href="/{{ @schema.nspname }}">
				<img data-src="{{ @schema_icon }}" alt="{{ @schema.nspname }}" src="{{ @schema_logo }}" style="width:100px;">
				<div class="caption">
					<p>{{ @schema.nspname }}</p>
				</div>
				</a>
			</div>
	  	</li>
	</repeat>
</ul>