<h2>Table Statistics</h2>
<br />
<table class="table">
	<thead>
        <tr>
          <th>Rows</th>
          <th>Columns</th>
          <th>Updated</th>
          <th>status</th>
        </tr>
      </thead>
      <tbody>
      	<tr>
      		<td>{{ @rows }}</td>
      		<td>{{ @columns }}</td>
      		<td>{{ @latest_update }}</td>
      		<td>{{ @status }}</td>
      		</tr>
      </tbody>
</table>
<br/><br />